### ISSUE TITLE
Text field autoFocus doesn't work in a portal

### ISSUE THREAD

**Issue by j-tai** [httptoolkit/react-reverse-portal#36]
If you have a text field in a portal, the `autoFocus` attribute doesn't work. The text field isn't automatically focused.

Is this a bug, or is this expected to happen? In the latter case, is there a workaround?

https://codesandbox.io/s/wonderful-wilbur-4niwtl?file=/src/App.js

```jsx
import {createHtmlPortalNode, InPortal, OutPortal} from 'react-reverse-portal';

export default function App() {
  const node = createHtmlPortalNode();
  return (
    <div className="App">
      <InPortal node={node}>
        <input type="text" autoFocus />
      </InPortal>
      <OutPortal node={node} />
    </div>
  );
}
```

**Comment by pimterry** [comment]
This is probably unavoidable I think. Browsers place lots of restrictions on exactly how autofocus works to avoid accessibility issues and confusing focus jumps. There's lots of cases where autofocus won't work automatically with single-page app rendering like this, even without portals involved.

I suspect the standard browser heuristic is to ignore autofocus changes unless it happens directly from a user interaction or it's set before the page is fully loaded. Presumably the async portal injection isn't considered by browsers as a reasonable trigger for autofocus. 

You'll need to manage the focus manually, probably with a ref and `ref.current.focus()`.

If you find something in this library that's causing this, or there's anything we can do here to help with that, I'm open to ideas, but for now I'm going to close this as expected behaviour.
